# Generated by Django 6.0.3 on 2026-03-27 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('previous_year', 'Previous Year'), ('previous_month', 'Previous Month')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('window_date', models.DateField()),
                ('window_start', models.TimeField()),
                ('window_end', models.TimeField()),
                ('sales', models.PositiveIntegerField(default=0)),
                ('interviews', models.PositiveIntegerField(default=0)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='scheduling.pointofsale')),
            ],
            options={
                'verbose_name': 'POS Metrics',
                'verbose_name_plural': 'POS Metrics',
                'ordering': ['pos__cdb_code', 'window_date', 'window_start'],
                'unique_together': {('pos', 'reference_type', 'period_start', 'period_end', 'window_date', 'window_start', 'window_end')},
            },
        ),
    ]
