# Generated by Django 6.0.3 on 2026-03-27 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdb_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('pos_type', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(blank=True, choices=[('Strategic', 'Strategic'), ('Prime', 'Prime'), ('BaseLine', 'BaseLine'), ('Developing', 'Developing')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('territory', models.CharField(blank=True, max_length=100)),
                ('chain', models.CharField(blank=True, max_length=100)),
                ('contractor', models.CharField(blank=True, max_length=100)),
                ('warehouse', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Point of Sale',
                'verbose_name_plural': 'Points of Sale',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('programme_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Exclusive', 'Exclusive'), ('Radical', 'Radical')], max_length=20)),
                ('base_city', models.CharField(blank=True, max_length=100)),
                ('team', models.CharField(blank=True, choices=[('SOUTH TEAM', 'South Team'), ('NORTH TEAM', 'North Team')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('programme_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Exclusive', 'Exclusive'), ('Radical', 'Radical')], max_length=20)),
                ('out_of_premises', models.BooleanField(default=False)),
                ('week_label', models.CharField(blank=True, max_length=10)),
                ('action', models.CharField(blank=True, choices=[('Executed', 'Executed'), ('Cancelled', 'Cancelled'), ('Change Visit', 'Change Visit'), ('Double Visit', 'Double Visit')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('comments_meeting', models.TextField(blank=True)),
                ('pos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='scheduling.pointofsale')),
                ('promoter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='scheduling.promoter')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='scheduling.schedule')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
