# Generated by Django 6.0.3 on 2026-03-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_schedule_included_pos_schedule_included_promoters'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
